export const slides = [
    { image: "/img/covers/Antidepressants.jpg", text: "Antidepressants" },
    { image: "/img/covers/Check.jpg", text: "Check" },
    { image: "/img/covers/Meant to Be.jpg", text: "Meant to Be" },
    { image: "/img/covers/Two.png", text: "Two" },
    { image: "/img/covers/It Boy.jpg", text: "It Boy" },
    { image: "/img/covers/Lil' Freak.jpg", text: "Lil' Freak" },
    { image: "/img/covers/Pho'real.jpg", text: "Pho'real" },
    { image: "/img/covers/Goodness Gracious.jpg", text: "Goodness Gracious" },
    { image: "/img/covers/Still.jpg", text: "Still" },
    { image: "/img/covers/Touch Grass.jpg", text: "Touch Grass" },
    { image: "/img/covers/Sophisticated.jpg", text: "Sophisticated" },
    { image: "/img/covers/Piccolo.jpg", text: "Piccolo" },
    { image: "/img/covers/Mathematics.jpg", text: "Mathematics" },
    { image: "/img/covers/Yoga.jpg", text: "Yoga" },
    { image: "/img/covers/Take a Trip.jpg", text: "Take a Trip" },
    { image: "/img/covers/Edamame.jpg", text: "Edamame" },
    { image: "/img/covers/Wussup.jpg", text: "Wussup" },
    { image: "/img/covers/Bad to the Bone.jpg", text: "Bad to the Bone" },
    { image: "/img/covers/Help Herself.jpg", text: "Help Herself" },
    { image: "/img/covers/WaWaWa.jpg", text: "WaWaWa" },
    { image: "/img/covers/Backwards.jpg", text: "Backwards" },
    { image: "/img/covers/Imma.jpg", text: "Imma" },
    { image: "/img/covers/Jack Money Bean.jpg", text: "Jack Money Bean" },
    { image: "/img/covers/Astrology.jpg", text: "Astrology" },
    { image: "/img/covers/What Would Baby Do.jpg", text: "What Would Baby Do?" },
    { image: "/img/covers/Quarantine Freestyle.jpg", text: "Quarantine Freestyle" },
    { image: "/img/covers/Mememe.jpg", text: "Mememe" },
    { image: "/img/covers/Off the Goop.jpg", text: "Off the Goop" },
    { image: "/img/covers/Welcome to Chilis.jpg", text: "Welcome to Chilis" },
    { image: "/img/covers/Iunno.jpg", text: "Iunno" },
    { image: "/img/covers/Shining on My Ex.jpg", text: "Shining on My Ex" },
    { image: "/img/covers/Slop.jpg", text: "Slop" },
    { image: "/img/covers/Lalala.jpg", text: "Lalala" }
];